bot:
  name: "Bot Infograted" # Bot Name
  online: true # Make the bot online when running
  commandPrefix: "!" # Command Prefix to give command to the bot
  syncHistory: false # Sync message history

rules:
  validGroups:
    - "120363404034113965@g.us": "Bot Infograted"
    - "120363419870703207@g.us": "informatika integrated💻"

logger:
  level: "info" # Logging level
  logDir: "./logs" # Log directory name
